### PR TITLE
Update projects.csv

### PR DESCRIPTION
**Pull request by Ojonathan**
Project proposal
Numi is a calculator that can handle multiple operations at once.

### CODE REVIEW

**Comment by ploum** [comment]
Hi, 

That project is quite small but interesting. What's your motivation to contribute to that project? Have you already contributed to it?

**Comment by Ojonathan** [comment]
> Hi,
> 
> That project is quite small but interesting. What's your motivation to contribute to that project? Have you already contributed to it?

I have not contributed yet in this project but it is a utility that I use from time to time.
but I'm still looking for a good alternative for example the following

https://github.com/commons-app/apps-android-commons

**Comment by ploum** [comment]
The second project is even better but if you use the first one and have never contributed to it, I will accept it.

**Comment by Ojonathan** [comment]
finally I will choose the option of the wikipedia application https://github.com/commons-app/apps-android-commons

**Pull request merged**
