### PR TITLE
Ajout de ma contribution + suppression des anciens étudiants

### PR DESCRIPTION
**Pull request by dewita**

### CODE REVIEW

**Comment by ploum** [comment]
Why are you adding a .idea folder ?

**Comment by dewita** [comment]
I use IntelliJ Idea to open the project. Hence, there are some files added (by the program) to the project that doesn't need to be added here.

**Comment by ploum** [comment]
Then please fix the merge request with a gitignore.

**Comment by dewita** [comment]
Seems correct now?

**Pull request merged**
